In [6]:
import numpy as np

THE BASICS 


In [7]:
a = np.array([5,2,3,7,9,6] , dtype = 'int32')
print(a)

[5 2 3 7 9 6]


In [8]:
b = np.array([[1.0,2.0,3.0,4.0,5.0,6.0],[1.0,4.0,5.0,6.0,7.0,8.0]])
print(b)

[[1. 2. 3. 4. 5. 6.]
 [1. 4. 5. 6. 7. 8.]]


In [9]:
#get dimension
a.ndim

1

In [10]:
#get shape
b.shape

(2, 6)

In [11]:
#get type
b.dtype

dtype('float64')

In [12]:
#get size
b.itemsize

8

In [13]:
#get total size
a.nbytes  #a.size * a.itemsize same thing like .nbytes

24

ACCESSING AND CHANGING SPECIFIC ELEMENTS , ROWS , COLUMNS AND ETC

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
#get specific element[row , column]
a[1 , 5]

13

In [16]:
#get specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
#get specific column
a[: , 2]

array([ 3, 10])

In [18]:
#getting [start:endind:step]
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# get specific element (work outside in)
b[0,1,0]

3

In [22]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


DIFFERENT TYPE OF ARR

In [23]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [27]:
# Random decimal num
np.random.rand(3,2)

array([[0.52641444, 0.56584263],
       [0.90082182, 0.19272452],
       [0.63866989, 0.36704408]])

In [28]:
# Random Integer val
np.random.randint(1,8, size=(3,3))

array([[2, 2, 2],
       [7, 7, 3],
       [7, 7, 6]])

In [29]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 10

print(b)

[10  2  3]


MATH

In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a + 2


array([3, 4, 5, 6])

In [35]:
a - 2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [38]:
b = np.array([1,2,1,2])
a + b

array([2, 4, 4, 6])

In [39]:
a ** 2

array([ 1,  4,  9, 16])

In [40]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

LINEAR ALGEBRA

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
#Find the det
c = np.identity(3)
np.linalg.det(c)

1.0

STATISTICS

In [43]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [44]:
np.min(stats)

1

In [45]:
np.max(stats, axis=1)

array([3, 6])

In [46]:
np.sum(stats, axis=0) # axis - это измирение

array([5, 7, 9])

In [47]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)ter)

SyntaxError: unmatched ')' (1061596421.py, line 4)

In [48]:
after = before.reshape((4,2))
print(after)ter)

SyntaxError: unmatched ')' (786606996.py, line 2)

In [49]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

load data from file

In [51]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced Indexing

In [52]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])