In [1]:
import numpy as np

In [27]:
a = np.array([[1,2,3,4],[3,4,5,9]])
print(a)

[[1 2 3 4]
 [3 4 5 9]]


In [6]:
b = np.array([[1,2,3,4,5,6],[1,4,5,6,7,8]])
print(b)

[[1 2 3 4 5 6]
 [1 4 5 6 7 8]]


In [28]:
#get dimension
a.ndim

2

In [29]:
#get shape
b.shape

(2, 6)

In [9]:
#get type
b.dtype

dtype('int32')

In [30]:
#get size
b.itemsize

4

In [31]:
#get total size
a.nbytes

32

In [22]:
#get specific element[row , column]
b[0 , 1]

2

In [24]:
#get specific row 
b[0, :]

array([1, 2, 3, 4, 5, 6])

In [26]:
#get specific column
b[: , 2]

array([3, 5])